name: AI Powered Build Log Summary

on:
  push:
    branches:
      - 'dev'
  pull_request:
    types: [opened, synchronized, reopened, edited]
    branches:
      - 'dev'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build-image
        run: docker build --no-cache --progress=plain . -t test-image &> build_log.txt

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          ls
          pip install requests

      - name: Parse Summarize Build Log
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TEST_KEY }}
        run: python3 scripts/perplex.py build_log.txt

